feature/PN-10828
pagopa/pn-external-channels pull request #158
Opened 2024-04-29 12:56 UTC by fabriziolana

2024-04-30 13:07 UTC, AnaNiagu approved these changes

2024-05-06 09:48 UTC, vincenzo-racca-pa requested changes

2024-05-06 09:48 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/api/ReceivedMessageController.java
> +public class ReceivedMessageController {
utilizzerei il plugin di openapi per autogenerare le API, così da evitare discrepanze tra il file OpenAPI e il codice

2024-05-06 09:48 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/dao/ReceivedMessageDigitalCourtesyMailRequestEntity.java
> +@Data
Eviterei di inserire @Data perchè già ci sono @NoArgsConstructor, @EqualsAndhashCode, @Setter e i @Getter e aggiungerei solo il @ToString (vale anche per le altre entità)

2024-05-06 09:48 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/service/ExternalChannelsService.java
> +            receivedMessageEntityDaoDynamo.put(RequestsToReceivedMessagesMapper.map(digitalNotificationRequest));
Manca il .block, anche sulle altre put. La put viene comunque eseguita, ma solo perchè il Mono wrappa un CompletableFuture. Tuttavia così viene utilizzato un altro thread rispetto a quello del chiamante.

2024-05-07 10:41 UTC, vincenzo-racca-pa approved these changes

2024-05-07 10:41 UTC, merged