Feature/pn 1612 new mock
pagopa/pn-external-channels pull request #31
Opened 2022-09-28 15:55 UTC by vincenzo-racca-pa

PR da mergiare nel branch main (non develop).

2022-09-29 07:26 UTC, fabriziolana requested changes

2022-09-29 07:26 UTC, fabriziolana commented on docs/openapi/pn-external-channels/api-internal-v1.yaml
> +info:
Gli openapi client, se importati (come in questo caso), negli altri progetti li mettiamo dentro docs\wsclient\nome (in questo caso appunto pn-safe-storage)
Lascerei poi inalterata la posizione per quelli di pn-external-channels (che son quelli esposti)

2022-09-29 07:26 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/externalchannels/Application.java
>      public static void main(String[] args) {
Aggiungere l'heartbeat, che sennò mi sa che il nostro DEV lo riavvia di continuo


@RestController
	public static class HomeController {

		@GetMapping("")
		public String home() {
			return "Sono Vivo";
		}
	}

2022-09-29 07:26 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/externalchannels/dto/NotificationProgress.java
> +
Non si poteva fare una lista unica con un oggetto che descrivesse duration e codice?

2022-09-29 07:26 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/externalchannels/springbootcfg/RestTemplateFactory.java
> +//
La lascerei attiva, così a gratis viene propagato il trace_id

2022-09-29 07:26 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/externalchannels/springbootcfg/RestTemplateFactoryActivation.java
> +//}
Idem come precedente

2022-09-29 07:26 UTC, fabriziolana commented on src/main/resources/application.properties
> +pn.external-channels.safe-storage-cx-id-updatemetadata=pn-external-channels
da fare check con marco su che id usare (non so se poi ci sono problemi di permission, ecc ecc)

2022-09-29 12:34 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/Application.java
>      public static void main(String[] args) {
fatto negli ultimi commit

2022-09-29 12:34 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/springbootcfg/RestTemplateFactory.java
> +//
fatto negli ultimi commit

2022-09-29 12:34 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/springbootcfg/RestTemplateFactoryActivation.java
> +//}
fatto negli ultimi commit

2022-09-29 12:36 UTC, vincenzo-racca-pa commented on src/main/resources/application.properties
> +pn.external-channels.safe-storage-cx-id-updatemetadata=pn-external-channels
cambiato valore in pn-delivery

2022-09-29 12:41 UTC, fabriziolana approved these changes

2022-09-29 15:21 UTC, fabriziolana requested changes

2022-09-29 15:21 UTC, fabriziolana commented on scripts/aws/cfn/microservice.yml
> +              - !Ref ExternalChannelsPecOutputsQueueName
Qua mi sa che ci va ExternalChannelsOutputsQueueName
e togli riga 92/93.
cambia e rimuovi pure sopra.
toglili dai parametri configurati, che mi sa che il valore viene "iniettato" dal codice INFRA che genera il container, pure li ci va ExternalChannelsOutputsQueueName

2022-09-29 15:21 UTC, fabriziolana commented on src/main/resources/application.properties
> +job.cron-expression=${JOB_CRON_EXPRESSION:*/2 * * * * *}
non credo serva fare così, le properties del microservice sovrascrivono semplicemente quelle presenti

2022-09-30 09:41 UTC, vincenzo-racca-pa commented on src/main/resources/application.properties
> +job.cron-expression=${JOB_CRON_EXPRESSION:*/2 * * * * *}
effettivamente non serve esplicitarla. Eliminata nell'ultimo commit.

2022-09-30 12:44 UTC, vincenzo-racca-pa commented on scripts/aws/cfn/microservice.yml
> +              - !Ref ExternalChannelsPecOutputsQueueName
modifica effettuata nell'ultimo commit

2022-09-30 12:47 UTC, fabriziolana approved these changes

2022-09-30 13:45 UTC, merged