PN-2422 - Extends microservice templates according to required dashboard metrics
pagopa/pn-external-channels pull request #43
Opened 2022-10-25 14:48 UTC by danilosilvase

- Axtends microservice templates according to required dashboard metrics

2022-10-26 09:30 UTC, fdammassa requested changes

2022-10-26 09:30 UTC, fdammassa commented on scripts/aws/cfn/microservice.yml
> +            - !Ref ExternalChannelsElabResQueueARN
@danilosilvase duplicate Queue Arn the other one is `ExternalChannelsInputsQueueARN`

2022-10-26 12:28 UTC, danilosilvase commented on scripts/aws/cfn/microservice.yml
> +            - !Ref ExternalChannelsElabResQueueARN
done.

2023-01-23 08:25 UTC, fdammassa commented
Closing the PR because we are not adding dashboard for mocked service.

2023-01-23 08:25 UTC, closed without merging