Feature/pn 2389 paper
pagopa/pn-external-channels pull request #52
Opened 2022-12-15 10:44 UTC by vincenzo-racca-pa

2022-12-15 16:37 UTC, fabriziolana requested changes

2022-12-15 16:37 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/externalchannels/util/EventCodeIntForPaper.java
> +
qui errore mio che ti avevo detto i codici con __001__
ci vanno senza gli __
quindi 001, 002, ecc.

2022-12-15 16:37 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/externalchannels/util/EventMessageUtil.java
> +    public static final String AR = "__AR__";
anche qui penso siano tutti senza __

2022-12-15 16:37 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/externalchannels/util/EventMessageUtil.java
> +    public static final List<String> PAPER_CHANNELS = List.of(AR, "__890__", "__RI__", "__RS__");
idem come sopra

2022-12-16 11:12 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/util/EventCodeIntForPaper.java
> +
fatto

2022-12-16 11:12 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/util/EventMessageUtil.java
> +    public static final List<String> PAPER_CHANNELS = List.of(AR, "__890__", "__RI__", "__RS__");
fatto

2022-12-16 11:12 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/externalchannels/util/EventMessageUtil.java
> +    public static final String AR = "__AR__";
fatto

2022-12-16 11:22 UTC, fabriziolana approved these changes

2022-12-16 11:24 UTC, merged